### PR TITLE
rename to length-prefixed-message

### PR DESCRIPTION
**Pull request by daviddias**
also adds badgerss :) 

Will be PR'ing soon also to call multistream -> multicodec and multistream-select -> multistream as discussed on the train from Vienna to Berlin 🚅

### CODE REVIEW

**Comment by jbenet** [comment]
**shrug** i dont care much about this name. but people do tend to seriously discount verbosity when picking things to use

**Comment by daviddias** [comment]
Definitely not trying to paint any bike shed :) we can kept both names if you prefer, but it is at minimum good to mention that msg-stream has an implementation in Node.js called `length-prefixed-message`

**Comment by jbenet** [comment]
@diasdavid yeah for sure! i also like `lpm`. maybe it could be: "lpm-stream" instead? and write it out? not sure.

(reason i had named it msg-stream is https://github.com/jbenet/go-msgio but super down to go for lpm)

**Comment by yoshuawuyts** [comment]
To chip in: `lpm-stream` sounds neat and memorable to me.

**Comment by daviddias** [comment]
I've just updated this PR to follow the suggestion. @jbenet can we get it merged?

//cc @whyrusleeping

**Comment by daviddias** [comment]
merging with `lpm-stream` as it is the one everyone agrees :)

**Pull request merged**
